### PR TITLE
add blah.py script

### PR DESCRIPTION
**Pull request by vortigont**
it will rehash and update tools.json based on tools_source.json manifest file

Objects for each new tool MUST already exist in  `tools.json`

### CODE REVIEW

**Comment by vortigont** [comment]
@Jason2866 pls check this out

**Comment by Jason2866** [comment]
@vortigont A big thank you from me, for the done work. With a quick look over it, everything needed seems to be there nkw. A few not needed entrys. But deleting stuff is quickly done. Will do the little work left.

**Comment by vortigont** [comment]
to rehash a new tool from a release, need just update the url in `tools.json`, add `"rehash":true` key:val and run `tool_rehash.py` script. Hope this helps to automate it in future

**Comment by Jason2866** [comment]
@vortigont Yes, thanks a lot for the python tool. I had already a look at the tool code and noticed that it is very usefull to update or calculate the needed hash and size values!

**Pull request merged**
